/* Automatically generated by p4c-ebpf from packetProcessor.p4 on Wed Oct  9 21:44:13 2024
 */
#include "PA.h"
#include "ebpf_kernel.h"

enum ebpf_errorCodes {
    NoError,
    PacketTooShort,
    NoMatch,
    StackOutOfBounds,
    HeaderTooShort,
    ParserTimeout,
    ParserInvalidArgument,
};

#define EBPF_MASK(t, w) ((((t)(1)) << (w)) - (t)1)
#define BYTES(w) ((w) / 8)
#define write_partial(a, s, v) do { u8 mask = EBPF_MASK(u8, s); *((u8*)a) = ((*((u8*)a)) & ~mask) | (((v) >> (8 - (s))) & mask); } while (0)
#define write_partial_ex(a, w, s, v) do { *((u8*)a) = ((*((u8*)a)) & ~(EBPF_MASK(u8, w) << s)) | (v << s) ; } while (0)
#define write_byte(base, offset, v) do { *(u8*)((base) + (offset)) = (v); } while (0)
#define PTR_DIFF_BYTES(b, o) (ssize_t)((u8*)(b) - (u8*)(o))

void* memcpy(void* dest, const void* src, size_t num);

#define bpf_trace_message(fmt, ...)

REGISTER_START()
REGISTER_END()

SEC("prog")
int ebpf_filter(SK_BUFF *skb){
    bpf_printk("Packet received, len=%d\n", skb->len);
    struct headers hdr = {
        .ethernet = {
            .ebpf_valid = 0
        },
        .ipv4 = {
            .ebpf_valid = 0
        },
    };
    enum ebpf_errorCodes ebpf_errorCode = NoError;
    void* ebpf_packetStart = ((void*)(long)skb->data);
    u8* ebpf_headerStart = ebpf_packetStart;
    void* ebpf_packetEnd = ((void*)(long)skb->data_end);
    u8 pass = 0;
    u32 ebpf_zero = 0;
    unsigned char ebpf_byte;
    u32 ebpf_pkt_len = skb->len;

    goto start;
    parse_ipv4: {
/* extract(hdr.ipv4) */
        if ((u8*)ebpf_packetEnd < ebpf_headerStart + BYTES(160 + 0)) {
            ebpf_errorCode = PacketTooShort;
            goto reject;
        }

        hdr.ipv4.version = (u8)((load_byte(ebpf_headerStart, BYTES(0)) >> 4) & EBPF_MASK(u8, 4));
        hdr.ipv4.ihl = (u8)((load_byte(ebpf_headerStart, BYTES(4))) & EBPF_MASK(u8, 4));
        hdr.ipv4.diffserv = (u8)((load_byte(ebpf_headerStart, BYTES(8))));
        hdr.ipv4.totalLen = (u16)((load_half(ebpf_headerStart, BYTES(16))));
        hdr.ipv4.identification = (u16)((load_half(ebpf_headerStart, BYTES(32))));
        hdr.ipv4.flags = (u8)((load_byte(ebpf_headerStart, BYTES(48)) >> 5) & EBPF_MASK(u8, 3));
        hdr.ipv4.fragOffset = (u16)((load_half(ebpf_headerStart, BYTES(51))) & EBPF_MASK(u16, 13));
        hdr.ipv4.ttl = (u8)((load_byte(ebpf_headerStart, BYTES(64))));
        hdr.ipv4.protocol = (u8)((load_byte(ebpf_headerStart, BYTES(72))));
        hdr.ipv4.hdrChecksum = (u16)((load_half(ebpf_headerStart, BYTES(80))));
        hdr.ipv4.srcAddr = (u32)((load_word(ebpf_headerStart, BYTES(96))));
        hdr.ipv4.dstAddr = (u32)((load_word(ebpf_headerStart, BYTES(128))));

        hdr.ipv4.ebpf_valid = 1;
        ebpf_headerStart += BYTES(160);

;
         bpf_printk("IPv4 packet: src=%x, dst=%x\n", hdr.ipv4.srcAddr, hdr.ipv4.dstAddr);
         goto accept;
    }
    start: {
/* extract(hdr.ethernet) */
        if ((u8*)ebpf_packetEnd < ebpf_headerStart + BYTES(112 + 0)) {
            ebpf_errorCode = PacketTooShort;
            goto reject;
        }

        hdr.ethernet.dstAddr = (u64)((load_dword(ebpf_headerStart, BYTES(0)) >> 16) & EBPF_MASK(u64, 48));
        hdr.ethernet.srcAddr = (u64)((load_dword(ebpf_headerStart, BYTES(48)) >> 16) & EBPF_MASK(u64, 48));
        hdr.ethernet.etherType = (u16)((load_half(ebpf_headerStart, BYTES(96))));

        hdr.ethernet.ebpf_valid = 1;
        ebpf_headerStart += BYTES(112);

;
 bpf_printk("Ethernet packet: type=0x%x\n", hdr.ethernet.etherType);
        u16 select_0;
        select_0 = hdr.ethernet.etherType;
        if (select_0 == 0x800)goto parse_ipv4;
        if ((select_0 & 0x0) == (0x0 & 0x0))goto accept;
        else goto reject;
    }

    reject: {
        bpf_printk("Packet rejected\n");
        return TC_ACT_SHOT;
    }

    accept:
    {
        u8 hit;
        {
if (/* hdr.ethernet.isValid() */
            hdr.ethernet.ebpf_valid) {
if (/* hdr.ipv4.isValid() */
                hdr.ipv4.ebpf_valid) {
/* allow() */
{
                        pass = true;
                        bpf_printk("IPv4 packet allowed\n");
                    };                }

                else {
                    pass = true;
                    bpf_printk("Non-Ethernet packet allowed\n");                }
            }

            else {
                pass = true;            }

        }
    }
    ebpf_end:
    if (pass) {
        bpf_printk("Packet allowed\n");
        return TC_ACT_OK;
    }
        
    else {
        bpf_printk("Packet dropped\n");
        return TC_ACT_SHOT;
    }
        
}
char _license[] SEC("license") = "GPL";
