/* Automatically generated by p4c-ebpf from protocolClassifier.p4 on Wed Sep  4 14:49:50 2024
 */
#include "protocolClassifier.h"
#include "ebpf_kernel.h"

struct bpf_map_def SEC("maps") protocol_counter = {
    .type = BPF_MAP_TYPE_ARRAY,
    .key_size = sizeof(u32),
    .value_size = sizeof(u32),
    .max_entries = 256,
};

struct bpf_map_def SEC("maps") total_counter = {
    .type = BPF_MAP_TYPE_ARRAY,
    .key_size = sizeof(u32),
    .value_size = sizeof(u32),
    .max_entries = 1,
};

enum ebpf_errorCodes {
    NoError,
    PacketTooShort,
    NoMatch,
    StackOutOfBounds,
    HeaderTooShort,
    ParserTimeout,
    ParserInvalidArgument,
};

#define EBPF_MASK(t, w) ((((t)(1)) << (w)) - (t)1)
#define BYTES(w) ((w) / 8)
#define write_partial(a, s, v) do { u8 mask = EBPF_MASK(u8, s); *((u8*)a) = ((*((u8*)a)) & ~mask) | (((v) >> (8 - (s))) & mask); } while (0)
#define write_partial_ex(a, w, s, v) do { *((u8*)a) = ((*((u8*)a)) & ~(EBPF_MASK(u8, w) << s)) | (v << s) ; } while (0)
#define write_byte(base, offset, v) do { *(u8*)((base) + (offset)) = (v); } while (0)
#define PTR_DIFF_BYTES(b, o) (ssize_t)((u8*)(b) - (u8*)(o))

void* memcpy(void* dest, const void* src, size_t num);

#define bpf_trace_message(fmt, ...)

REGISTER_START()
REGISTER_TABLE(MyFilter_ipv4_classifier, BPF_MAP_TYPE_HASH, struct MyFilter_ipv4_classifier_key, struct MyFilter_ipv4_classifier_value, 512)
BPF_ANNOTATE_KV_PAIR(MyFilter_ipv4_classifier, struct MyFilter_ipv4_classifier_key, struct MyFilter_ipv4_classifier_value)
REGISTER_TABLE(MyFilter_ipv4_classifier_defaultAction, BPF_MAP_TYPE_ARRAY, u32, struct MyFilter_ipv4_classifier_value, 1)
BPF_ANNOTATE_KV_PAIR(MyFilter_ipv4_classifier_defaultAction, u32, struct MyFilter_ipv4_classifier_value)
REGISTER_END()

SEC("prog")
int ebpf_filter(SK_BUFF *skb){
    struct headers hdr = {
        .ethernet = {
            .ebpf_valid = 0
        },
        .ipv4 = {
            .ebpf_valid = 0
        },
    };
    enum ebpf_errorCodes ebpf_errorCode = NoError;
    void* ebpf_packetStart = ((void*)(long)skb->data);
    u8* ebpf_headerStart = ebpf_packetStart;
    void* ebpf_packetEnd = ((void*)(long)skb->data_end);
    u8 accept = 0;
    u32 ebpf_zero = 0;
    unsigned char ebpf_byte;
    u32 ebpf_pkt_len = skb->len;

    goto start;
    parse_ipv4: {
/* extract(hdr.ipv4) */
        if ((u8*)ebpf_packetEnd < ebpf_headerStart + BYTES(160 + 0)) {
            ebpf_errorCode = PacketTooShort;
            goto reject;
        }

        hdr.ipv4.version = (u8)((load_byte(ebpf_headerStart, BYTES(0)) >> 4) & EBPF_MASK(u8, 4));
        hdr.ipv4.ihl = (u8)((load_byte(ebpf_headerStart, BYTES(4))) & EBPF_MASK(u8, 4));
        hdr.ipv4.diffserv = (u8)((load_byte(ebpf_headerStart, BYTES(8))));
        hdr.ipv4.totalLen = (u16)((load_half(ebpf_headerStart, BYTES(16))));
        hdr.ipv4.identification = (u16)((load_half(ebpf_headerStart, BYTES(32))));
        hdr.ipv4.flags = (u8)((load_byte(ebpf_headerStart, BYTES(48)) >> 5) & EBPF_MASK(u8, 3));
        hdr.ipv4.fragOffset = (u16)((load_half(ebpf_headerStart, BYTES(51))) & EBPF_MASK(u16, 13));
        hdr.ipv4.ttl = (u8)((load_byte(ebpf_headerStart, BYTES(64))));
        hdr.ipv4.protocol = (u8)((load_byte(ebpf_headerStart, BYTES(72))));
        hdr.ipv4.hdrChecksum = (u16)((load_half(ebpf_headerStart, BYTES(80))));
        hdr.ipv4.srcAddr = (u32)((load_word(ebpf_headerStart, BYTES(96))));
        hdr.ipv4.dstAddr = (u32)((load_word(ebpf_headerStart, BYTES(128))));

        hdr.ipv4.ebpf_valid = 1;
        ebpf_headerStart += BYTES(160);

;
         goto accept;
    }
    start: {
/* extract(hdr.ethernet) */
        if ((u8*)ebpf_packetEnd < ebpf_headerStart + BYTES(112 + 0)) {
            ebpf_errorCode = PacketTooShort;
            goto reject;
        }

        hdr.ethernet.dstAddr = (u64)((load_dword(ebpf_headerStart, BYTES(0)) >> 16) & EBPF_MASK(u64, 48));
        hdr.ethernet.srcAddr = (u64)((load_dword(ebpf_headerStart, BYTES(48)) >> 16) & EBPF_MASK(u64, 48));
        hdr.ethernet.etherType = (u16)((load_half(ebpf_headerStart, BYTES(96))));

        hdr.ethernet.ebpf_valid = 1;
        ebpf_headerStart += BYTES(112);

;
        u16 select_0;
        select_0 = hdr.ethernet.etherType;
        if (select_0 == 0x800)goto parse_ipv4;
        if ((select_0 & 0x0) == (0x0 & 0x0))goto accept;
        else goto reject;
    }

    reject: {
        return TC_ACT_SHOT;
    }

    accept:
    {
        u8 hit;
        {
            accept = true;
            if (/* hdr.ipv4.isValid() */
            hdr.ipv4.ebpf_valid) {
/* ipv4_classifier_0.apply() */
                {
                    /* construct key */
                    struct MyFilter_ipv4_classifier_key key = {};
                    key.field0 = hdr.ipv4.protocol;
                    /* value */
                    struct MyFilter_ipv4_classifier_value *value = NULL;
                    /* perform lookup */
                    value = BPF_MAP_LOOKUP_ELEM(MyFilter_ipv4_classifier, &key);
                    if (value == NULL) {
                        /* miss; find default action */
                        hit = 0;
                        value = BPF_MAP_LOOKUP_ELEM(MyFilter_ipv4_classifier_defaultAction, &ebpf_zero);
                    } else {
                        hit = 1;
                    }
                    if (value != NULL) {
                        /* run action */
                        switch (value->action) {
                            case MYFILTER_IPV4_CLASSIFIER_ACT_MYFILTER_COUNT_PACKET: 
                                {
                                    u32 protocol = hdr.ipv4.protocol;
                                    u32 *protocol_count = bpf_map_lookup_elem(&protocol_counter, &protocol);
                                    if (protocol_count) {
                                        __sync_fetch_and_add(protocol_count, 1);
                                    }

                                    u32 total_index = 0;
                                    u32 *total_count = bpf_map_lookup_elem(&total_counter, &total_index);
                                    if (total_count) {
                                        __sync_fetch_and_add(total_count, 1);
                                    }
                                    
                                    accept = true;
                                }
                                break;
                            default:
                                return TC_ACT_SHOT;
                        }
                    } else {
                        return TC_ACT_SHOT;
;
                    }
                }
;            }

        }
    }
    ebpf_end:
    if (accept)
        return TC_ACT_OK;
    else
        return TC_ACT_SHOT;
}
char _license[] SEC("license") = "GPL";
