apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-master
spec:
  nodeName: k8s-master3  # deploy to master 
  containers:
  - name: dev-container
    image: ubuntu:24.04
    command: ["/bin/sleep", "3650d"]
    resources:
      limits:
        memory: "1Gi"
        cpu: "500m"
    volumeMounts:
    - name: shared-data
      mountPath: /shared-data
  volumes:
  - name: shared-data
    emptyDir: {}
  initContainers:
  - name: install-tools
    image: ubuntu:24.04
    command: ["/bin/sh", "-c"]
    args:
      - apt-get update && 
        DEBIAN_FRONTEND=noninteractive apt-get install -y 
        build-essential 
        gcc 
        g++ 
        gdb 
        curl 
        iputils-ping 
        net-tools 
        vim 
        wget 
        git &&
        apt-get clean &&
        rm -rf /var/lib/apt/lists/*
    volumeMounts:
    - name: shared-data
      mountPath: /shared-data
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-node1
spec:
  nodeName: k8s-node1  # deploy to node1
  containers:
  - name: dev-container
    image: ubuntu:24.04
    command: ["/bin/sleep", "3650d"]
    resources:
      limits:
        memory: "1Gi"
        cpu: "500m"
    volumeMounts:
    - name: shared-data
      mountPath: /shared-data
  volumes:
  - name: shared-data
    emptyDir: {}
  initContainers:
  - name: install-tools
    image: ubuntu:24.04
    command: ["/bin/sh", "-c"]
    args:
      - apt-get update && 
        DEBIAN_FRONTEND=noninteractive apt-get install -y 
        build-essential 
        gcc 
        g++ 
        gdb 
        curl 
        iputils-ping 
        net-tools 
        vim 
        wget 
        git &&
        apt-get clean &&
        rm -rf /var/lib/apt/lists/*
    volumeMounts:
    - name: shared-data
      mountPath: /shared-data
