apiVersion: v1
kind: Pod
metadata:
  name: test-pod-master
spec:
  nodeName: k8s-master3  # deploy to master 
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-node1
spec:
  nodeName: k8s-node1  # deploy to node1
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/sleep", "3650d"]